### ISSUE TITLE
race condition in 1.4.2

### ISSUE THREAD

**Issue by regisa** [nathanjsweet/throttlelock#1]
FYI, I think there's an undetected race condition in 1.4.2.
Works fine in 1.5.2
You can run the test in 1.4.2 and see that you won't get the logs from the tasks

https://golang.org/doc/go1.5 <- search for waitgroup

**Comment by nathanjsweet** [comment]
As in, waitgroup has a race condition?

**Comment by nathanjsweet** [comment]
yeah, I guess it would involve switching the lock and the wait around. I should have thought of that, but honestly, why else would you use `WaitGroup` except among goroutines? I guess it should like this:

``` go
tl.C.L.Lock()
tl.W.Add(1)
```

not this:

``` go
tl.W.Add(1)
tl.C.L.Lock()
```

**Comment by regisa** [comment]
I tried this and it still didn't look right when running it. I ended up putting a small delay in the loop that was adding tasks. It's on my list of things to play with when I properly try to learn GO :)

**Comment by nathanjsweet** [comment]
I fixed this issue. The WaitGroup wait function wasn't being called all the time. So I added code in which you specify how many waiters you expect to eventually wait. It should work now, but notice the change in instantiation.
